config/routes.rb
Localguides::Application.routes.draw do
  

  resources :reviews

  resources :tours

  resources :attractions

  resources :users

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attractions }
    end
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attraction }
    end
  end

  # GET /attractions/new
  # GET /attractions/new.json
  def new
    @attraction = Attraction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attraction }
    end
  end

  # GET /attractions/1/edit
  def edit
    @attraction = Attraction.find(params[:id])
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(params[:attraction])

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render json: @attraction, status: :created, location: @attraction }
      else
        format.html { render action: "new" }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attractions/1
  # PUT /attractions/1.json
  def update
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      if @attraction.update_attributes(params[:attraction])
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy

    respond_to do |format|
      format.html { redirect_to attractions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attractions.each do |attraction| %>
  <tr>
    <td><%= attraction.name %></td>
    <td><%= attraction.longitude %></td>
    <td><%= attraction.latitude %></td>
    <td><%= link_to 'Show', attraction %></td>
    <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
    <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @attraction.name %>
</p>

<p>
  <b>Longitude:</b>
  <%= @attraction.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @attraction.latitude %>
</p>


<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>